package db

import (
	"encoding/json"
	"time"
)

// EnrollmentToken is a single-use, short-lived token the platform BE
// mints when a SOC admin clicks "Send Executor" (R-I.10.re1 +
// 2026-10-06-runner-security-hardening-plan.md §10.10). The token is
// generated by the platform BE (out of scope for this slice) and
// embedded into the install bundle. The executor's install.sh exchanges
// it for a long-lived mTLS cert via POST /api/v1/executor/enroll.
//
// The token IS the proof of tenant binding at enrollment time — the
// handler does NOT trust any tenant_id from the request body. The
// tenant binding lives on the EnrollmentToken row.
//
// Fields map to the enrollment_tokens table (migration v2.19.19,
// defined in db/sql/migration_2_19_19.go).
type EnrollmentToken struct {
	// TokenHash is the lowercase hex SHA-256 digest of the plaintext
	// token. The plaintext is NEVER persisted on the server — it
	// lives only in the install bundle the customer's IT admin runs.
	// Format: 64-char hex (matches the executor's existing
	// auth-token-hash convention).
	TokenHash string `db:"token_hash" json:"-"`

	// TenantID is the customer the executor will be bound to. Set at
	// token-mint time by the platform BE, immutable.
	TenantID string `db:"tenant_id" json:"tenant_id" binding:"required"`

	// DeploymentZoneIDsJSON is the JSON-encoded list of deployment
	// zones the executor is allowed to claim jobs for. Empty list
	// means "no zones" (the executor cannot claim any project-task
	// until the operator assigns at least one zone).
	DeploymentZoneIDsJSON string `db:"deployment_zone_ids" json:"-"`

	// ExecutorName is the human-readable label the platform BE
	// proposes for the executor. The executor may keep this or
	// override at /register; for the new flow we use it directly at
	// /enroll so the operator does not have to repeat the work.
	ExecutorName string `db:"executor_name" json:"executor_name"`

	// Hostname is the proposed hostname (matches the install host).
	// Used at /enroll as the executor's hostname (operator may
	// override via re-registration).
	Hostname string `db:"hostname" json:"hostname"`

	// ExpiresAt is the wall-clock time the token stops being valid.
	// Default TTL is 5 minutes (EnrollmentTokenTTL). Tokens past this
	// time are rejected with 410 enrollment_token_expired.
	ExpiresAt time.Time `db:"expires_at" json:"expires_at" binding:"required"`

	// ConsumedAt is set when /enroll successfully exchanges the
	// token. NULL until consumed. A second consume attempt returns
	// 409 enrollment_token_already_consumed (atomic check).
	ConsumedAt *time.Time `db:"consumed_at" json:"consumed_at,omitempty"`

	// ConsumedByExecutorID is the public ExecutorID (ULID) the
	// server minted at consume time. NULL until consumed. Used to
	// reconcile the executor row's creation to the token row.
	ConsumedByExecutorID *string `db:"consumed_by_executor_id" json:"consumed_by_executor_id,omitempty"`

	// CreatedAt is the wall-clock time the token was minted.
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// EnrollmentTokenTTL is the lifetime of an enrollment token (5 minutes
// per R-I.10.re1 plan row). Long enough for a customer's IT admin to
// receive the email + ssh to the host + run install.sh + wait for the
// executor's bootstrap call to round-trip; short enough that a leaked
// token becomes useless within minutes.
const EnrollmentTokenTTL = 5 * time.Minute

// DeploymentZoneIDs decodes the JSON list of deployment zone IDs.
// Returns nil on empty or decode error (mirrors Executor.Platforms()).
func (t EnrollmentToken) DeploymentZoneIDs() []string {
	if t.DeploymentZoneIDsJSON == "" {
		return nil
	}
	var out []string
	if err := json.Unmarshal([]byte(t.DeploymentZoneIDsJSON), &out); err != nil {
		return nil
	}
	return out
}

// SetDeploymentZoneIDs encodes the zone list as JSON for storage.
// Empty input is stored as the empty string.
func (t *EnrollmentToken) SetDeploymentZoneIDs(ids []string) error {
	if len(ids) == 0 {
		t.DeploymentZoneIDsJSON = ""
		return nil
	}
	b, err := json.Marshal(ids)
	if err != nil {
		return err
	}
	t.DeploymentZoneIDsJSON = string(b)
	return nil
}

// IsExpired reports whether the token is past its ExpiresAt.
func (t EnrollmentToken) IsExpired() bool {
	return !t.ExpiresAt.After(time.Now().UTC())
}

// IsConsumed reports whether the token has already been exchanged.
func (t EnrollmentToken) IsConsumed() bool {
	return t.ConsumedAt != nil
}