#!/usr/bin/env bash
# install.sh — SentraOps executor first-boot installer (Linux)
#
# This script is what the customer's IT admin runs after clicking
# the "Send Executor" link in the SOC console. It is invoked as a
# single command:
#
#   curl -sSL https://sentraops.example.com/install/<token> | sudo bash
#
# The script:
#   1. Detects the platform (Linux + init system)
#   2. Writes the executor binary + bootstrap.json + config.yaml to
#      /etc/sentraops-executor/  (mode 0600 on every secret file)
#   3. Writes the systemd unit file
#   4. Runs `sentraops-executor --bootstrap` to exchange the token
#      for a long-lived mTLS cert
#   5. On success, enables + starts the service
#   6. On failure, leaves the bundle in place + prints a clear error
#      so the IT admin can retry
#
# Wazuh-style one-command install. The customer never edits YAML.
#
# Env vars consumed (passed by the SOC console's wrapper):
#   SENTRAOPS_EXECUTOR_BOOTSTRAP_TOKEN   The single-use enrollment token
#   SENTRAOPS_EXECUTOR_SERVER_URL        The SentraOps server URL
#   SENTRAOPS_EXECUTOR_TENANT_ID         The customer's tenant ID
#   SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID  The customer's deployment zone
#   SENTRAOPS_EXECUTOR_BINARY_URL        Where to download the executor binary
#                                          (default: <server_url>/download/executor-linux-amd64)
#
# R-I.10.re3: combined installer + first-boot bootstrap (Wazuh-style).
# R-I.5 (Linux playbook) updated to call this script instead of doing
# the install inline.

set -euo pipefail

# Colors only when stdout is a TTY. No ANSI in piped/log contexts.
if [[ -t 1 ]]; then
  RED=$'\e[31m'
  GRN=$'\e[32m'
  YEL=$'\e[33m'
  RST=$'\e[0m'
else
  RED="" GRN="" YEL="" RST=""
fi

log() { printf '%s\n' "$*" >&2; }
fail() { log "${RED}ERROR:${RST} $*"; exit 1; }
ok() { log "${GRN}✓${RST} $*"; }

# Required input.
: "${SENTRAOPS_EXECUTOR_BOOTSTRAP_TOKEN:?missing SENTRAOPS_EXECUTOR_BOOTSTRAP_TOKEN}"
: "${SENTRAOPS_EXECUTOR_SERVER_URL:?missing SENTRAOPS_EXECUTOR_SERVER_URL}"
: "${SENTRAOPS_EXECUTOR_TENANT_ID:?missing SENTRAOPS_EXECUTOR_TENANT_ID}"

if [[ -z "${SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID:-}" ]]; then
  fail "missing SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID"
fi

# System paths. Mode 0700 on the install dir so the cert is
# owner-only-accessed.
INSTALL_DIR="/etc/sentraops-executor"
BIN_DIR="/usr/local/bin"
SERVICE_FILE="/etc/systemd/system/sentraops-executor.service"
EXEC_BIN="${BIN_DIR}/sentraops-executor"

mkdir -p "${INSTALL_DIR}"
chmod 0700 "${INSTALL_DIR}"

# ---- 1. Download the executor binary ----------------------------------
BINARY_URL="${SENTRAOPS_EXECUTOR_BINARY_URL:-${SENTRAOPS_EXECUTOR_SERVER_URL%/}/download/executor-linux-amd64}"

log "Downloading executor from ${BINARY_URL} ..."
TMP_BIN="$(mktemp /tmp/sentraops-executor.XXXXXX)"
if ! curl -fsSL --retry 3 -o "${TMP_BIN}" "${BINARY_URL}"; then
  rm -f "${TMP_BIN}"
  fail "could not download executor binary from ${BINARY_URL}"
fi
chmod 0755 "${TMP_BIN}"
mv "${TMP_BIN}" "${EXEC_BIN}"
ok "Installed executor binary to ${EXEC_BIN}"

# ---- 2. Write the config.yaml -----------------------------------------
CONFIG_PATH="${INSTALL_DIR}/config.yaml"
CERT_PATH="${INSTALL_DIR}/cert.pem"
KEY_PATH="${INSTALL_DIR}/key.pem"
CA_PATH="${INSTALL_DIR}/ca.pem"

cat > "${CONFIG_PATH}" <<EOF
# Generated by SentraOps install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# The bootstrap_token line is wiped automatically after a successful
# exchange so a stolen disk image cannot replay it.
server_url: "${SENTRAOPS_EXECUTOR_SERVER_URL}"
tenant_id: "${SENTRAOPS_EXECUTOR_TENANT_ID}"
deployment_zone_id: "${SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID}"
client_cert_path: "${CERT_PATH}"
client_key_path: "${KEY_PATH}"
server_ca_file: "${CA_PATH}"
bootstrap_token: "${SENTRAOPS_EXECUTOR_BOOTSTRAP_TOKEN}"
bootstrap_url: "${SENTRAOPS_EXECUTOR_SERVER_URL}"
EOF
chmod 0600 "${CONFIG_PATH}"
ok "Wrote config to ${CONFIG_PATH} (mode 0600)"

# ---- 3. Write the systemd unit ----------------------------------------
cat > "${SERVICE_FILE}" <<'EOF'
[Unit]
Description=SentraOps Executor (customer-side deployment daemon)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/sentraops-executor --config /etc/sentraops-executor/config.yaml
Restart=on-failure
RestartSec=10s
User=root
Group=root

# Hardening (matches R-I.6's systemd unit shape — keep consistent).
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/etc/sentraops-executor
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true

[Install]
WantedBy=multi-user.target
EOF
ok "Wrote systemd unit to ${SERVICE_FILE}"

# ---- 4. Run bootstrap mode (exchanges token for cert) ---------------
log "Exchanging enrollment token for long-lived mTLS cert ..."
if ! "${EXEC_BIN}" --bootstrap --config "${CONFIG_PATH}"; then
  fail "bootstrap failed. The executor binary returned non-zero. " \
       "The install is left in a retryable state; re-run this script to retry."
fi
ok "Bootstrap complete; cert + key + CA bundle written to ${INSTALL_DIR}"

# ---- 5. Enable + start the service ----------------------------------
systemctl daemon-reload
systemctl enable sentraops-executor.service
systemctl restart sentraops-executor.service
ok "Service enabled + started"

# ---- 6. Final report ------------------------------------------------
log ""
log "${GRN}✅ Done. SentraOps executor is online.${RST}"
log ""
log "Useful commands:"
log "  systemctl status sentraops-executor"
log "  journalctl -u sentraops-executor -f"
log "  ${EXEC_BIN} --dry-run --config ${CONFIG_PATH}"
log ""
log "Config + cert live at:"
log "  ${INSTALL_DIR}/"
log ""
log "Tenant: ${SENTRAOPS_EXECUTOR_TENANT_ID}"
log "Zone:   ${SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID}"
log "Server: ${SENTRAOPS_EXECUTOR_SERVER_URL}"