# install.ps1 — SentraOps executor first-boot installer (Windows)
#
# This script is what the customer's IT admin runs in an elevated
# PowerShell after clicking the "Send Executor" link in the SOC
# console. It is invoked as a single command:
#
#   iex (irm https://sentraops.example.com/install/<token>)
#
# The script:
#   1. Detects the platform (Windows + arch)
#   2. Writes the executor binary + bootstrap.json + config.yaml to
#      C:\ProgramData\SentraOps\Executor\  (ACL: owner-only on every
#      secret file)
#   3. Installs + starts the service via NSSM (non-Sucking Service
#      Manager) — bundled in the executor binary's directory
#   4. Runs `sentraops-executor.exe --bootstrap` to exchange the
#      token for a long-lived mTLS cert
#   5. On success, starts the service
#   6. On failure, leaves the bundle in place + prints a clear error
#      so the IT admin can retry
#
# Wazuh-style one-command install. The customer never edits YAML.
#
# Env vars consumed (passed by the SOC console's wrapper):
#   $env:SENTRAOPS_EXECUTOR_BOOTSTRAP_TOKEN   The single-use enrollment token
#   $env:SENTRAOPS_EXECUTOR_SERVER_URL        The SentraOps server URL
#   $env:SENTRAOPS_EXECUTOR_TENANT_ID         The customer's tenant ID
#   $env:SENTRAOPS_EXECUTOR_DEPLOYMENT_ZONE_ID  The customer's deployment zone
#   $env:SENTRAOPS_EXECUTOR_BINARY_URL        Where to download the executor binary
#
# R-I.10.re3: combined installer + first-boot bootstrap (Wazuh-style).
# R-I.5 (Windows playbook) updated to call this script instead of
# doing the install inline.

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$BootstrapToken,
    [Parameter(Mandatory=$true)][string]$ServerURL,
    [Parameter(Mandatory=$true)][string]$TenantID,
    [Parameter(Mandatory=$true)][string]$DeploymentZoneID,
    [string]$BinaryURL,
    [string]$InstallDir = "${env:ProgramData}\SentraOps\Executor",
    [string]$BinaryPath = "$InstallDir\sentraops-executor.exe",
    [string]$ConfigPath = "$InstallDir\config.yaml",
    [string]$CertPath   = "$InstallDir\cert.pem",
    [string]$KeyPath    = "$InstallDir\key.pem",
    [string]$CAPath     = "$InstallDir\ca.pem",
    [string]$ServiceName = "SentraOpsExecutor"
)

$ErrorActionPreference = "Stop"

function Write-Ok  { param($m) Write-Host "✓ $m" -ForegroundColor Green }
function Write-Err { param($m) Write-Host "ERROR: $m" -ForegroundColor Red; exit 1 }

if (-not $BinaryURL) { $BinaryURL = "$($ServerURL.TrimEnd('/'))/download/executor-windows-amd64.exe" }

# ---- 0. Admin check --------------------------------------------------
$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Err "this script must run from an elevated PowerShell (Run as Administrator)"
}

# ---- 1. Create the install dir ---------------------------------------
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

# Restrict ACL on the install dir (Administrators + SYSTEM only).
$acl = Get-Acl $InstallDir
$acl.SetAccessRuleProtection($true, $false)
$rules = @(
    New-Object System.Security.AccessControl.FileSystemAccessRule(
        "BUILTIN\Administrators","FullControl","ContainerInherit,ObjectInherit","None","Allow"),
    New-Object System.Security.AccessControl.FileSystemAccessRule(
        "NT AUTHORITY\SYSTEM","FullControl","ContainerInherit,ObjectInherit","None","Allow")
)
$rules | ForEach-Object { $acl.AddAccessRule($_) }
Set-Acl $InstallDir $acl

# ---- 2. Download the executor binary ---------------------------------
Write-Host "Downloading executor from $BinaryURL ..."
try {
    Invoke-WebRequest -Uri $BinaryURL -OutFile $BinaryPath -UseBasicParsing -TimeoutSec 30
} catch {
    Write-Err "could not download executor binary: $($_.Exception.Message)"
}
Write-Ok "Installed executor binary to $BinaryPath"

# ---- 3. Write the config.yaml ----------------------------------------
$configBody = @"
# Generated by SentraOps install.ps1 on $(Get-Date -Format o)
# The bootstrap_token line is wiped automatically after a successful
# exchange so a stolen disk image cannot replay it.
server_url: "$ServerURL"
tenant_id: "$TenantID"
deployment_zone_id: "$DeploymentZoneID"
client_cert_path: "$CertPath"
client_key_path: "$KeyPath"
server_ca_file: "$CAPath"
bootstrap_token: "$BootstrapToken"
bootstrap_url: "$ServerURL"
"@
Set-Content -Path $ConfigPath -Value $configBody -Encoding UTF8 -Force
# Apply the same restrictive ACL to the config file.
$acl = Get-Acl $ConfigPath
$acl.SetAccessRuleProtection($true, $false)
$rules | ForEach-Object { $acl.AddAccessRule($_) }
Set-Acl $ConfigPath $acl
Write-Ok "Wrote config to $ConfigPath (ACL: Administrators + SYSTEM only)"

# ---- 4. Install the Windows service via NSSM ------------------------
# We ship nssm.exe alongside the executor binary; the operator
# downloads it as part of the bundle OR we curl it from the same
# place the binary came from. For V1 we use New-Service (built-in)
# and accept that SimplePath; production may swap to NSSM later.
$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($null -eq $svc) {
    Write-Host "Creating Windows service $ServiceName ..."
    New-Service -Name $ServiceName -BinaryPathName "`"$BinaryPath`" --config `"$ConfigPath`"" -DisplayName "SentraOps Executor" -StartupType Automatic | Out-Null
} else {
    Write-Host "Service $ServiceName already exists; updating binary path ..."
    sc.exe config $ServiceName binPath= "`"$BinaryPath`" --config `"$ConfigPath`"" | Out-Null
}
Write-Ok "Service $ServiceName installed"

# ---- 5. Run bootstrap mode (exchange token for cert) ----
Write-Host "Exchanging enrollment token for long-lived mTLS cert ..."
$proc = Start-Process -FilePath $BinaryPath -ArgumentList @("--bootstrap","--config",$ConfigPath) -Wait -PassThru -NoNewWindow
if ($proc.ExitCode -ne 0) {
    Write-Err "bootstrap failed (exit $proc.ExitCode). The install is left in a retryable state; re-run this script to retry."
}
Write-Ok "Bootstrap complete; cert + key + CA bundle written to $InstallDir"

# ---- 6. Start the service -------------------------------------------
Start-Service -Name $ServiceName
Write-Ok "Service started"

# ---- 7. Final report -----------------------------------------------
Write-Host ""
Write-Host "Done. SentraOps executor is online." -ForegroundColor Green
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Get-Service $ServiceName"
Write-Host "  Get-EventLog -LogName Application -Source $ServiceName -Newest 20"
Write-Host "  & '$BinaryPath' --dry-run --config '$ConfigPath'"
Write-Host ""
Write-Host "Tenant: ${TenantID}"
Write-Host "Zone:   ${DeploymentZoneID}"
Write-Host "Server: ${ServerURL}"